modify imgcat with the command "imgcat -u + url" get rid of caching part

diff --git a/source/utilities/imgcat b/source/utilities/imgcat
--- a/source/utilities/imgcat
+++ b/source/utilities/imgcat
@@ -62,21 +62,6 @@ function show_help() {
     echo "   or: cat filename | imgcat" 1>& 2
 }
 
-# create image directory under the directory of imgcat
-function img_folder() {
-	dir_name="$(echo ~)/.iterm2/image_collection"
-	if [ ! -d dir_name ]; then
-	    mkdir -p $dir_name
-	fi
-}
-
-# create a list to check if the picture has been downloaded
-function make_list() {
-	if [ ! -f $dir_name/list.txt ]; then
-		touch $dir_name/list.txt
-	fi
-}
-
 ## Main
 
 if [ -t 0 ]; then
@@ -93,6 +78,7 @@ fi
 
 # Look for command line flags.
 while [ $# -gt 0 ]; do
+
     case "$1" in
     -h|--h|--help)
         show_help
@@ -101,6 +87,29 @@ while [ $# -gt 0 ]; do
     -p|--p|--print)
         print_filename=1
         ;;
+	-u|--u|--url)
+        if curl --output /dev/null --silent --head --fail "$2"; then # check if the url is downloadable
+			# create a file with unique file name
+			file=$(mktemp -t curlimg) || { echo "Failed creating file"; return; }
+			# download file and save it into the unique file name just created
+    		curl -s "$2" > $file || { echo "Failed to curl file"; return; }
+			# reset argument of url to the corresponding unique file
+            has_stdin=f
+            print_image "$file" 1 "$(base64 < "$file")" "$print_filename"
+			# delete the downloaded file
+			rm $file
+			# only modify second argument in order to keep running option "-u"
+			# shift will remove the first arguement "-u"
+			set -- ${@:1:1} "-u" ${@:3}
+			# every url has been done, so exit
+			if [ "$#" -eq 2 ]; then
+				exit
+			fi
+		else
+			error "imgcat: $2: No such file or url"
+			exit 2
+		fi	
+		;;
     -*)
         error "Unknown option flag: $1"
         show_help
@@ -108,28 +117,6 @@ while [ $# -gt 0 ]; do
       ;;
     *)
         if [ -r "$1" ] ; then
-            has_stdin=f
-            print_image "$1" 1 "$(base64 < "$1")" "$print_filename"
-        elif curl --output /dev/null --silent --head --fail "$1"; then # check if the url is downloadable
-			img_folder
-			make_list
-			# check if already downloaded from the url
-			if grep -q $1 $dir_name/list.txt; then 
-				# get file name from the list
-				md5_name=$(echo "$(grep $1 $dir_name/list.txt)" | sed 's/.* \([0-9a-f]\)/\1/')
-			else
-				# download file with temporal name called tmp
-				curl $1 -o "$dir_name/tmp" > /dev/null 2>&1
-
-				# rename tmp to its md5 value
-				md5_name=$(echo "$(md5 $dir_name/tmp)" | sed 's/MD5 (.*) = \([0-9a-f]\)/\1/')
-				mv "$dir_name/tmp" "$dir_name/$md5_name"
-
-				# add new download file into the list
-				echo "$1 $md5_name" >> $dir_name/list.txt
-			fi
-			# reset argument of url to the corresponding md5_name
-			set -- "$dir_name/$md5_name"
             has_stdin=f
             print_image "$1" 1 "$(base64 < "$1")" "$print_filename"
 		else	
